# Generated by Django 5.0.2 on 2024-02-13 20:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ввода записи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата деактивации записи')),
                ('number', models.IntegerField(unique=True, verbose_name='Номер контракта')),
            ],
            options={
                'verbose_name': 'Номер контракта',
                'verbose_name_plural': 'Номера контрактов',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ввода записи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата деактивации записи')),
                ('name', models.CharField(max_length=250, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Производитель',
                'verbose_name_plural': 'Производители',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ввода записи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата деактивации записи')),
                ('name', models.CharField(max_length=250, verbose_name='Наименование товара')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_manufacturer', to='credits.manufacturer', verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Наименование товара',
                'verbose_name_plural': 'Наименование товаров',
            },
        ),
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата редактирования')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата ввода записи')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата деактивации записи')),
                ('contract', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loan_contract', to='credits.contract', verbose_name='Заявка на кредит')),
                ('products', models.ManyToManyField(related_name='loan_product', to='credits.product', verbose_name='Товары')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
